### PR TITLE
Add STOPSIGNAL command

### PR DESCRIPTION
**Pull request by ptzafrir**

### CODE REVIEW

**Comment by ptzafrir** [comment]
@tverbeke  any comment on this PR? who can approve it?

**Comment by tverbeke** [comment]
Hi @ptzafrir ; actually we donated the docker editor to the Eclipse Foundation and it is now shipped as part of the Linux Tools Project. Sources are up here: https://github.com/eclipse/linuxtools/tree/master/containers/org.eclipse.linuxtools.docker.editor

**Comment by ptzafrir** [comment]
Thanks for the info. I've created a new PR in the new project

**Comment by lifeofguenter** [comment]
@ptzafrir any possibilities to backport it back to this project? I am happy to do the organization and also to host the eclipse update url.

I just feel installing linuxtools is a bit huge for my use-case of only needing a dockerfile interpreter.

**Comment by ptzafrir** [comment]
I don't have commit rights to this project. If you would like to fork it, and host the eclipse update url I will gladly open a PR with the same fix to your fork.
You should probably gain permission from @tverbeke for licensing rights (if any)

**Pull request closed without merging**
